[package]
name = "below_derive"
version = "0.2.0"
authors = ["Daniel Xu <dlxu@fb.com>", "Facebook"]
edition = "2018"
description = "Proc macros for below"
repository = "https://github.com/facebookincubator/below"
license = "Apache-2.0"

[lib]
test = false
doctest = false
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["extra-traits", "fold", "full", "visit", "visit-mut"] }
