[package]
name = "below-config"
version = "0.3.0"
authors = ["Daniel Xu <dlxu@fb.com>", "Facebook"]
edition = "2018"
description = "Configerations for below"
repository = "https://github.com/facebookincubator/below"
license = "Apache-2.0"

[dependencies]
anyhow = "1.0"
cgroupfs = { version = "0.3.0", path = "../cgroupfs" }
once_cell = "1.4"
serde = { version = "1.0.126", features = ["derive", "rc"] }
toml = "=0.5.7"

[dev-dependencies]
tempdir = "0.3"
