name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build_test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build docker image
      run: >
        docker build
        -t below
        --target build
        .
    - name: Run tests
      # Skip tests that require host to have cgroup2
      run: >
        docker run below scripts/test_all.sh
